[[bin]]
name = "917b"
path = "problems/working/917/B.rs"

[dependencies]
memoise = "0.3.2"
rustc-hash = "1.1.0"

[dependencies.proconio]
features = ["derive"]
version = "0.4.3"

[dev-dependencies]
rand = "0.8.5"

[package]
edition = "2021"
name = "rust"
version = "0.1.0"
